Fix missing void keyword
fletcher97/ft_irc pull request #10
Opened 2023-03-25 15:14 UTC by sebamiro

2023-03-25 16:52 UTC, fletcher97 requested changes
Files in tst still require void

2023-03-25 17:08 UTC, fletcher97 approved these changes
Looks good to me

2023-03-25 20:23 UTC, fletcher97 commented
This should fix #6

2023-03-27 15:24 UTC, gemartin99 approved these changes

2023-03-27 15:24 UTC, merged