Feature/configuration
fletcher97/ft_irc pull request #31
Opened 2023-04-29 14:36 UTC by gemartin99

2023-04-29 18:03 UTC, fletcher97 requested changes

2023-04-29 18:03 UTC, fletcher97 commented on inc/Configuration.hpp
all gets should be const and return const values

2023-04-29 18:03 UTC, fletcher97 commented on inc/Communications.hpp
Class arguments should be close together and follow the same naming conventions

2023-04-29 18:03 UTC, fletcher97 commented on irc_config.txt
We should try to follow some kind of convention for the format like toml.

What I'm really referring to is the fact that you give admin 3 different value instead of having an array...

2023-04-29 18:03 UTC, fletcher97 commented on src/classes/Communications.cpp
> +	if ((port == 0) && (psswd == 0)) {
Pointers should be compared to pointers (aka NULL)

2023-04-29 18:03 UTC, fletcher97 commented on src/classes/Configuration.cpp
> +ft_irc::Configuration::Configuration(const ft_irc::Configuration&)
This method needs to be implemented

2023-04-29 18:03 UTC, fletcher97 commented on src/classes/Configuration.cpp
> +ft_irc::Configuration::operator=(const ft_irc::Configuration&)
All arguments should be copied no?

2023-04-29 18:03 UTC, fletcher97 commented on src/classes/Configuration.cpp
> +	std::ifstream config_file("irc_config.txt");
The file name should probably be a macro

2023-04-29 18:03 UTC, fletcher97 commented on src/classes/Configuration.cpp
> +		std::cerr << "Error: Could not open configuration file" << std::endl;
You should use log

2023-04-29 18:03 UTC, fletcher97 commented on src/classes/Configuration.cpp
> +			std::string key = line.substr(0, equal);
If you remove one everywhere you should do it only here and be done with it

2023-04-29 18:09 UTC, fletcher97 commented
Also there are no tests. Config shouldn't be hard to test

2023-05-05 20:17 UTC, fletcher97 requested changes
Constructor should initialize all class attributes

2023-05-10 08:53 UTC, fletcher97 approved these changes

2023-05-10 09:01 UTC, sebamiro approved these changes

2023-05-10 09:01 UTC, merged