Added bases methods for Client, Server, Channel and Communication
fletcher97/ft_irc pull request #5
Opened 2023-03-12 21:09 UTC by sebamiro

Added some methods for every class, and a main that runs the server, every client that connects, creates a class in the client map of the server.
Channel, and read messages still to do.

2023-03-12 21:12 UTC, gemartin99 approved these changes

2023-03-12 21:13 UTC, fletcher97 commented
Why has all this been added to the com's branch? Also, shouldn't @gemartin99 be tue one responsible for this?

2023-03-12 21:14 UTC, sebamiro commented
Sorry I still getting use to git hub, we did it together tho

2023-03-16 01:25 UTC, fletcher97 requested changes
Some things need to be changed. check comments on review for more detail

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +// struct	ChannelMode
Don't add commented code to master. You can leave it in the branch but remove it for master.

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +	// ChannelMode	_mode;
Don't add commented code to master. You can leave it in the branch but remove it for master.

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +	// size_t	maxClients; Usefull?
Don't add commented code to master. You can leave it in the branch but remove it for master.

If you think it will be useful just add it

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +	// std::vector<Client *> getClients() const;
Don't add commented code to master. You can leave it in the branch but remove it for master.

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +	// bool	isInChannel(const std::string& nickname);
Don't add commented code to master. You can leave it in the branch but remove it for master.

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +	// std::vector<Channel&>	getChannels() const; TODO
Don't add commented code to master. You can leave it in the branch but remove it for master.

If something need to be done then it shouldn't be added to master. Implement it before submitting for review or remove it and start to work on it in a different branch

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +	//void handleCommand TODO
Don't add commented code to master. You can leave it in the branch but remove it for master.

If something need to be done then it shouldn't be added to master. Implement it before submitting for review or remove it and start to work on it in a different branch

2023-03-16 01:25 UTC, fletcher97 commented on src/Channel.cpp
> +Channel::Channel() :	_name(),
What happened to the formatting here?

2023-03-16 01:25 UTC, fletcher97 commented on src/Channel.cpp
> +// std::vector<Client*>
Don't add commented code to master. You can leave it in the branch but remove it for master.

If something need to be done then it shouldn't be added to master. Implement it before submitting for review or remove it and start to work on it in a different branch

2023-03-16 01:25 UTC, fletcher97 commented on src/Client.cpp
> +ClientMode::ClientMode() :	a(false),
Tabs should be 4 spaces

2023-03-16 01:25 UTC, fletcher97 commented on src/Client.cpp
> +Client::Client(int fd, struct sockaddr_in socket) :	_fd(fd),
Tabs should be 4 spaces

2023-03-16 01:25 UTC, fletcher97 commented on src/Client.cpp
> +Client::Client(const Client &c) :	_fd(c._fd),
Tabs should be 4 spaces

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +#include <vector>
There shouldn't be any useless includes. No code uses vectors apart from the commented ones

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +enum	ClientStatus
This could be moved inside client and renamed to status. It should be public but don't put it in the same section as the function. Try to keep variables and functions in their own sections

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +struct	ClientMode
This could be moved inside client and renamed to Mode. It can be public but don't put it in the same section as the function. Try to keep variables and functions in their own sections

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +struct	ClientMode
You could also make it protected and add functions to turn the different modes on. (If they are only set at construction time the factory would take care of this)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Communications.hpp
> +	void write_error(const char *s);
Variables and functions should be in different sections even if they have the same scope

2023-03-16 01:25 UTC, fletcher97 commented on inc/Communications.hpp
> +  void run();
Indentations needs to be fixed

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +	Client&	getClient(const std::string& nickname);
Functions that don't alter the object should be marked as const

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +	std::vector<Client*>	getClients();
Functions that don't alter the object should be marked as const

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +	typedef std::map<int, Client*>::iterator clients_iterator;
typedef could be moved up to be closer to the variables

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +	Communications*	_communications;
References should be used when possible. You can initiate the communications and pass it by reference to the constructor of the server

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +	void	run();
Zero parameter functions should have void in them

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +	Channel();
Zero parameter functions should have void in them

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
>  	~Channel();
Zero parameter functions should have void in them

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +	std::string	getName() const;
Zero parameter functions should have void in them

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +	ClientMode();
Zero parameter functions should have void in them

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
>  	~Client();
Zero parameter functions should have void in them

2023-03-16 01:25 UTC, fletcher97 commented on inc/Communications.hpp
> +#define MAX_CLIENTS 124
Includes should be the first thing. Defines should be placed after the includes

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +	bool	a;
Given that there are only 7 modes I would consider using a single char to use each bit and creating enums or defines for each mode

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +	bool	a;
Speed can go up as you can perform math operations instead of if/else/switch and you would be using less memory. win-win

2023-03-16 01:25 UTC, fletcher97 commented on inc/Communications.hpp
> +	typedef std::vector<pollfd>::iterator	pfds_iterator;
Typedef could be moved closer to the variables?

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +	void	delClient(Client& client);
There shouldn't be any prototype that doesn't have an implementation

2023-03-16 01:25 UTC, fletcher97 commented on inc/Server.hpp
> +	bool	isChannel(const std::string& name) const;
There shouldn't be any prototype that doesn't have an implementation

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +	void	setName(std::string name);
When possible use references

2023-03-16 01:25 UTC, fletcher97 commented on src/Channel.cpp
> +	if (this->_clients.count(client.getFd()) == 1)
When you have an if that returns true else returns false you should simply return the condition of the if

2023-03-16 01:25 UTC, fletcher97 commented on src/Channel.cpp
Functions should have logging for their actions. At least debug level should be added and info where appropriate

2023-03-16 01:25 UTC, fletcher97 commented on src/Channel.cpp
>  Channel &Channel::operator=(const Channel& c) {
Return type should be placed on the previous line to conform with code style

2023-03-16 01:25 UTC, fletcher97 commented on src/Channel.cpp
> +	this->_name = c.getName();
The object's parameter should be directly accessed instead of calling a function and adding overhead

2023-03-16 01:25 UTC, fletcher97 commented on inc/Channel.hpp
> +	std::string	getName() const;
Consider returning const references

2023-03-16 01:25 UTC, fletcher97 commented on src/Client.cpp
> +		default : return false;
Functions shouldn't silently fail. Throwing an exception would be a better alternative

2023-03-16 01:25 UTC, fletcher97 commented on src/Client.cpp
> +		case 'a' : this->_mode.a = true;
Switches don't work like if/else. A break is needed at the end of each case to exit the switch.

2023-03-16 01:25 UTC, fletcher97 commented on inc/Client.hpp
> +	void	setMode(char c);
Set and unset work in the same way. The only difference is if it's set to true or false. This could be passed as an extra parameter and it would remove an extra function from the code.

2023-03-16 01:25 UTC, fletcher97 commented on src/Client.cpp
> +		case 'a' : this->_mode.a = false;
Switches don't work like if/else. A break is needed at the end of each case to exit the switch.

2023-03-16 01:25 UTC, fletcher97 commented on src/Channel.cpp
All functions that accept a parameter and do not change it should mark it as const

2023-03-16 01:25 UTC, fletcher97 commented on src/Client.cpp
Functions should have logging for their actions. At least debug level should be added and info where appropriate

2023-03-16 01:25 UTC, fletcher97 commented on src/Client.cpp
All functions that accept a parameter and do not change it should mark it as const

2023-03-16 01:25 UTC, fletcher97 commented on src/Client.cpp
> +	this->_fd = c.getFd();
The object's parameter should be directly accessed instead of calling a function and adding overhead

2023-03-16 01:25 UTC, fletcher97 commented on src/Client.cpp
> +// std::vector<Channel&>
Code shouldn't be left commented. If it is not required it should be deleted. If it's needed it should be implemented or moved to a different branch

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +																													_pfds(s._pfds),
Indentation needs to be fixed

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +Communications &Communications::operator=(const Communications &s) {
return type should be on the line above to follow the code style

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +	while (42)
A proper check of a variable should be added so that a command to shutdown the server can change it and thus exit cleanly. A simple TODO should do for now

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +//throw std::invalid_argument("Invalid nickname");
Code shouldn't be left commented

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +Communications::write_error(const char *s) {
Indentation should use tabs

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +    exit (EXIT_FAILURE);
EXIT_FAILURE isn't defined and thus code doesn't compile (at least on linux)

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +Communications::init(int port, std::string psswd) {
Indentation should use tabs

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +Communications::addPfd(int fd) {
Indentation should use tabs and be uniform

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
Functions should have logging for their actions. At least debug level should be added and info where appropriate

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
All functions that accept a parameter and do not change it should mark it as const

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +Communications::write_error(const char *s) {
Is this really needed or would just the logging system work?

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +Communications::write_error(const char *s) {
Function names should be self explanatory. calling exit on a function named write isn't intuitive

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +Communications::init(int port, std::string psswd) {
Error messages should be more explicit

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +Communications::init(int port, std::string psswd) {
Usage of object attributes should be preceded by this keyword

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +    std::cout << "Listening on port " << port << std::endl;
Logging should be used to display current status of server

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +			std::cerr << "Error poll" << std::endl;
Logging should be used to display issues

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +Communications::run(void) {
Usage of object attributes should be preceded by this keyword

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +		//SEND MESSAGES PENDING
All comments for tasks that need to be done should start with TODO:

2023-03-16 01:25 UTC, fletcher97 commented on src/Communications.cpp
> +	return _fd;
Usage of object attributes should be preceded by this keyword

2023-03-16 01:25 UTC, fletcher97 commented on src/main.cpp
> +		return (0);//error
Exit code zero means ok. A proper error code should be returned

2023-03-16 01:25 UTC, fletcher97 commented on src/main.cpp
> +	int port = atoi(argv[1]);
atoi is undefined. A header for it should be included

2023-03-16 01:25 UTC, fletcher97 commented on src/main.cpp
> +	int port = atoi(argv[1]);
This should be checked to make sure no errors occured

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
>  	LOG_INFO("Removed server: " << this->_name);
_name was removed from  the class definition. This line no longer compiles

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
Server should be a singleton. All copy and assignment operators should be private and throw an error when called.

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +																	_channels(s._channels),
Indentation should be checked

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +			return *(*it).second;
Dereferencing may cause confusion. Using -> would be preferable

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +	return *(*_clients.find(fd)).second;
Dereferencing may cause confusion. Using -> would be preferable

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +	channel->setName(name);
Why is set name called here?

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +		clients_vec.push_back((*it).second);
Dereferencing may cause confusion. Using -> would be preferable

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +		channels_vec.push_back((*it).second);
Dereferencing may cause confusion. Using -> would be preferable

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +Server::getChannels() {
Why does this function generate a new vector instead of return the map used by the server?
Also channels should be refenrences and not pointers

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +Server::getClients() {
Why does this function generate a new vector instead of return the map used by the server?
Also client should be refenrences and not pointers

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +// void
Code shouldn't be left commented

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +
Empty lines shouldn't have white spaces (tabs)

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +	int	clientFd = accept(_communications->getFd(), reinterpret_cast<struct sockaddr*>(&clientAddress), &socklen);
Lines should have white spaces at the end

2023-03-16 01:25 UTC, fletcher97 commented on src/Server.cpp
> +	_clients[clientFd] = new Client(clientFd, clientAddress);
Lines should'n have white spaces at the end

2023-03-16 01:26 UTC, fletcher97 requested changes
Some things need to be changed. check comments on review for more detail

2023-03-23 17:58 UTC, fletcher97 approved these changes
OK

2023-03-23 17:58 UTC, merged